[tool.poetry]
name = "mecapacktools"
version = "1.3.9"
description = "Outils de base pour Mecapack"
authors = ["Informatique Mecapack <informatique@mecapack.com>"]
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]


[tool.poetry.dependencies]
python = "^3.11"
arrow = "^1.2.3"
openpyxl = "^3.1.2"
sortedcontainers = "^2.4.0"
requests = {version = "^2.28.2", optional = true}
suds = {version = "^1.1.2", optional = true}
xmltodict = {version = "^0.13.0", optional = true}
pypyodbc = {version = "^1.3.6", optional = true}
pywin32 = {version = "^306", optional = true}
paramiko = {version ="^3.2.0", optional = true}

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^23.3.0"
isort = "^5.12.0"
sphinx = "^6.1.3"
sphinx-rtd-theme = "^1.2.0"
sphinx-markdown-builder = "^0.5.5"

[tool.poetry.extras]
excel = ["pywin32"]
Sql = ["pypyodbc"]
WebServices = ["requests","xmltodict","suds"]
FTP = ["paramiko"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
