[project]
name = "globgroups"
description = """Expands glob groups like foo{bar,baz} -> ["foobar", "foobaz"]"""
requires-python = ">=3.9"
authors = [
  { name = "Techcable" },
]
keywords = ["glob", "globset", "globgroups", "wildcard", "expansion"]
license = { text = "MIT License" }
readme = "README.md"
# Version computed by setuptools_scm
dynamic = ["version"]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Topic :: System :: System Shells",
  "Topic :: Terminals",
  "Topic :: Utilities",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]

dependencies = [
    "funcparserlib==1.*",
    "typing_expansions>=4.4",
]

[project.urls]
"Bug Tracker" = "https://github.com/Techcable/globgroups.py/issues"
"Source Code" = "https://github.com/Techcable/globgroups.py"

[build-system]
requires = ["setuptools>=61.0", "setuptools_scm[toml]>=6.2", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.setuptools_scm]
# NOTE: Using a version file avoids some overhead
#
# This file is explicitly ignored by version control.
write_to = "src/globgroups/_version.py"

