[project]
name = "cringelord"
version = "1.0.2"
description = """
    Environment-sensitive configuration management tool that allows you use
    the same code with different configurations.

    You'll no longer need if-else statements or multiple files (one for each
    environment) to get your code working in multiple environments. 
"""
license = {file = "LICENSE.txt"}

authors = [
    { name = "Thomas Vanhelden", email = "thomas.vanhelden@cegeka.com" }
]
dependencies = [
    "click>=8.1.7",
    "pydantic>=2.6.1",
    "pyyaml>=6.0.1",
    "pydantic-yaml>=1.2.1",
    "mkdocs-material>=9.5.10",
    "mkdocs-git-revision-date-localized-plugin>=1.2.4",
    "mkdocs-git-authors-plugin>=0.7.2",
    "tomli==2.0.1",
]
readme = "README.md"
requires-python = ">= 3.9"

[project.scripts]
hello = "cringelord:hello"

[project.urls]
Documentation = "https://cringelord-heerlijkeheer-806eb581859167e3efa6c9df4ab5e4bf17987f.gitlab.io/"
Repository = "https://gitlab.com/HeerlijkeHeer/cringelord"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.0.1",
    "pytest-cov>=4.1.0",
    "pytest-randomly>=3.15.0",
    "pytest-sugar>=1.0.0",
    "pytest-mock>=3.12.0",
    "pdbpp==0.10.3",
    "bump-my-version==0.19.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/cringelord"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[tool.hatch.build.targets.sdist]
src-dir = "src"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q -vv -s --disable-warnings --cache-clear -v --cov=cringelord --verbose --cov-report term:skip-covered --cov-report xml:test_reports/cov.xml"
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test"]
python_functions = ["test"]
pythonpath = [".", "src", "cringelord"]

[tool.bumpversion]
current_version = "1.0.2"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
commit = true
tag = true
sign_tags = true
tag_name = "{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
message = "Bump version: {current_version} → {new_version}"
commit_args = "--gpg-sign"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'

[tool.cringelord]
config_file = "cringe-config.yaml"
mode = "ALL"
src_dir = "src"
default_environment = "local"
templates = []
exception_on_missing_setting = false

[[tool.cringelord.environments.production]]
description = "Our production environment."
aliases = [
    "prd",
    "prod",
    "oc",
    "okd"
]

[[tool.cringelord.environments.local]]
description = "Developer laptop for local testing."
aliases = [
    "test",
    "dev",
    "laptop"
]
