[tool.poetry]
name = "mcitemlib"
version = "0.1.1"
description = "A library for creating and editing Minecraft items using python."
authors = ["Amp"]
license = "MIT"
readme = "README.md"
keywords=["minecraft", "item", "block"]
repository = "https://github.com/Amp63/mcitemlib"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
