[project]
name = "trycicle"
version = "0.1.1"
description = "Try CI jobs locally"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX",
    "License :: OSI Approved :: MIT License",
]
requires-python = "~= 3.11"
dependencies = [
    "pyyaml ~= 6.0",
    "docker ~= 7.0",
    "click ~= 8.1",
]

[[project.authors]]
name = "Paul Hooijenga"
email = "paul@founda.com"

[project.urls]
"Homepage" = "https://gitlab.com/phooijenga/trycicle"

[project.scripts]
trycicle = "trycicle.cli:main"

[build-system]
requires = ["flit_core ~= 3.9"]
build-backend = "flit_core.buildapi"

[tool.mypy]
strict = true
enable_error_code = "redundant-self,ignore-without-code"

[[tool.mypy.overrides]]
module = ["docker.*"]
ignore_missing_imports = true

[tool.ruff]
fix = true
show-fixes = true

[tool.ruff.lint]
select = ["F", "E", "W", "I", "UP", "RUF", "C90"]
unfixable = ["F841", "F842"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.coverage.run]
omit = ["*/__main__.py"]
