[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pageserver"
version = "0.0.1"
authors = [
  { name="song zirui", email="pochnsong@163.com" },
]
description = "a asyncio web framework."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pochnsong/pageserver.git"
Documentation = "https://github.com/pochnsong/pageserver/wiki"
Repository = "https://github.com/pochnsong/pageserver.git"
Issues = "https://github.com/pochnsong/pageserver/issues"

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["src"]  # ["."] by default
namespaces = false

[tool.setuptools]
include-package-data = true