[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "phanos"
version = "0.3.2"
authors = [
  { name="Miroslav BuliÄka", email="bulickamiroslav@gmail.com" },
]
description = "Python client to gather data for Prometheus logging in server with multiple instances and workers."
readme = "README.md"
requires-python = ">=3.10.6"
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: System :: Monitoring",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pip>=23.1.2",
    "pika>=1.3.2",
    "aio_pika>=9.2",
    "orjson>=3.9",
    ]

[tool.hatch]
directory = "src"
name = "phanos"


[project.urls]
"Homepage" = "https://github.com/kajotgames/phanos"
"Bug Tracker" = "https://github.com/kajotgames/phanos/issues"