[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "django-calendards"
version = "0.1.0"
description = "One of the my demiansoft apps"
authors = [{name = "Hyungjin Kim", email = "hj3415@gmail.com"}]
license = {file = "LICENSE"}
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
    "Django >= 5.0.3",
]

[project.urls]
Home = "https://www.demiansoft.com"

[tool.flit.sdist]
# include = ["analyticsds/","calendards/","popupds/"]
exclude = [
    "django_calendards/_data/",
    "django_calendards/_mytester/",
    "django_calendards/_static/",
    "django_calendards/media/",
    "django_calendards/db.sqlite3",
    "django_calendards/manage.py",
]
