[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sapphire-renderer"
version = "0.0.9"
authors = [
  { name="Dark_Eden", email="darkedenc9@gmail.com" },
]
description = "A package to easely render simple 3d scenes"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/DarkEden-coding/Sapphire-Renderer"
"Bug Tracker" = "https://github.com/DarkEden-coding/Sapphire-Renderer/issues"
