[tool.poetry]
name = "stairsval"
version = "0.4.2"
description = ""
authors = ["jrzkaminski <86363785+jrzkaminski@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11,"
matplotlib = ">=3.6.2"
numpy = ">=1.25.0"
stairs-mro = ">=0.2.1"
numpy-indexed = "0.3.5"
pandas = ">=2.0.0"
scipy = ">=1.8.0"
seaborn = ">=0.11.2"
reportlab = "*"
rich = ">=13.5.3"

[tool.poetry.dev-dependencies]
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
