[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "CTK_Desert"
version = "0.0.1"
dependencies = [
  "customtkinter>=5.2.0", 
  "Pillow>=9.4.0", 
  "numpy>=1.23.5"
]
requires-python = ">=3.8"
authors = [
  { name="Morad Sayed", email="Morad.S.Singer@gmail.com" },
]
description = "A GUI that uses the customtkinter library to create GUIs based on your need, so that you focus on the functionality of your application and not the design."
readme = "README.md"
keywords = ["CTK_Desert", "tkinter", "Customtkinter", "GUI", "APP", "beautiful", "design", "easy", "simple", "fast", "CTK"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

